postgresql: &postgresql
  adapter: postgresql
  encoding: utf8
  database: upaya_<%= Rails.env %>
  port: 5432

defaults: &defaults
  pool: 5
  host: localhost
  <<: *postgresql
  # timeout settings
  timeout: 5000
  reconnect: true
  connect_timeout: 2
  keepalives_idle: 30
  keepalives_interval: 10
  keepalives_count: 2
  checkout_timeout: 5
  reaping_frequency: 10

development:
  <<: *defaults

test:
  <<: *defaults

# cloud.gov database compatibility
<%
  begin
    services = JSON.parse(ENV['VCAP_SERVICES'])
    credentials = services['aws-rds'].first['credentials']
  rescue
    credentials = {}
  end
%>

<% if !credentials.empty? %>
production:
  adapter: postgresql
  encoding: unicode
  host: <%= credentials['host'] || 'localhost' %>
  port: <%= credentials['port'] || '3306' %>
  database: <%= credentials['db_name'] || '' %>
  username: <%= credentials['username'] || '' %>
  password: <%= credentials['password'] || '' %>
<% else %>
production:
  <<: *defaults
  database: <%= Figaro.env.database_name! %>
  username: <%= Figaro.env.database_username! %>
  host: <%= Figaro.env.database_host! %>
  password: <%= Figaro.env.database_password! %>
  sslmode: 'verify-full'
  sslrootcert: '/usr/local/share/aws/rds-combined-ca-bundle.pem'
<% end %>
